"""SQLAlchemy models + async engine.

The models mirror the DDL in marketpulse_spec.md exactly: same columns, types,
UUID primary keys via ``gen_random_uuid()``, the same CHECK constraints and
indexes. ``init_db()`` issues ``CREATE TABLE IF NOT EXISTS`` for local/first-run
convenience; on Railway the same schema is produced.
"""
from __future__ import annotations

from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode

from sqlalchemy import (
    CheckConstraint,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from config import settings


def _build_engine_url() -> tuple[str, dict]:
    """Return (url, connect_args), pulling ``sslmode`` out of the query string.

    asyncpg rejects libpq's ``sslmode`` query parameter (it wants an ``ssl``
    connect arg instead). Railway hands out URLs with ``?sslmode=require``, so we
    translate that here to avoid a confusing connection error.
    """
    url = settings.async_database_url
    parts = urlsplit(url)
    query = dict(parse_qsl(parts.query))
    connect_args: dict = {}
    sslmode = query.pop("sslmode", None)
    if sslmode in ("require", "verify-ca", "verify-full"):
        connect_args["ssl"] = True
    elif sslmode in ("disable",):
        connect_args["ssl"] = False
    new_url = urlunsplit(
        (parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment)
    )
    return new_url, connect_args


_engine_url, _connect_args = _build_engine_url()

engine = create_async_engine(
    _engine_url,
    echo=False,
    pool_pre_ping=True,
    connect_args=_connect_args,
)

AsyncSessionLocal = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


class Base(DeclarativeBase):
    pass


_UUID_PK = dict(
    primary_key=True,
    server_default=text("gen_random_uuid()"),
)


class Ticker(Base):
    __tablename__ = "tickers"

    id: Mapped[str] = mapped_column(UUID(as_uuid=True), **_UUID_PK)
    symbol: Mapped[str] = mapped_column(String(20), unique=True, nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    asset_class: Mapped[str] = mapped_column(String(20), nullable=False)
    last_fetched_at: Mapped[object | None] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )
    created_at: Mapped[object] = mapped_column(
        TIMESTAMP(timezone=True), server_default=text("NOW()")
    )

    sentiment_scores: Mapped[list["SentimentScore"]] = relationship(
        back_populates="ticker", cascade="all, delete-orphan"
    )
    headlines: Mapped[list["Headline"]] = relationship(
        back_populates="ticker", cascade="all, delete-orphan"
    )

    __table_args__ = (
        CheckConstraint(
            "asset_class IN ('stock','crypto','commodity')",
            name="ck_tickers_asset_class",
        ),
        Index("idx_tickers_symbol", "symbol"),
        Index("idx_tickers_asset_class", "asset_class"),
    )


class SentimentScore(Base):
    __tablename__ = "sentiment_scores"

    id: Mapped[str] = mapped_column(UUID(as_uuid=True), **_UUID_PK)
    ticker_id: Mapped[str] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tickers.id", ondelete="CASCADE"),
        nullable=False,
    )
    score: Mapped[float] = mapped_column(Float, nullable=False)
    positive_pct: Mapped[float] = mapped_column(Float, nullable=False)
    negative_pct: Mapped[float] = mapped_column(Float, nullable=False)
    neutral_pct: Mapped[float] = mapped_column(Float, nullable=False)
    headline_count: Mapped[int] = mapped_column(Integer, nullable=False)
    model_used: Mapped[str] = mapped_column(String(100), nullable=False)
    # Natural-language explanation of the aggregate sentiment, generated by the
    # model alongside the per-headline scores. Nullable: empty when no news.
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[object] = mapped_column(
        TIMESTAMP(timezone=True), server_default=text("NOW()")
    )

    ticker: Mapped["Ticker"] = relationship(back_populates="sentiment_scores")
    headlines: Mapped[list["Headline"]] = relationship(
        back_populates="sentiment_score", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("idx_sentiment_ticker_id", "ticker_id"),
        Index("idx_sentiment_created_at", text("created_at DESC")),
    )


class Headline(Base):
    __tablename__ = "headlines"

    id: Mapped[str] = mapped_column(UUID(as_uuid=True), **_UUID_PK)
    ticker_id: Mapped[str] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tickers.id", ondelete="CASCADE"),
        nullable=False,
    )
    sentiment_score_id: Mapped[str] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("sentiment_scores.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(String(50), nullable=False)
    individual_sentiment: Mapped[str] = mapped_column(String(10), nullable=False)
    individual_score: Mapped[float] = mapped_column(Float, nullable=False)
    confidence: Mapped[str] = mapped_column(String(10), nullable=False)
    published_at: Mapped[object | None] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True
    )
    created_at: Mapped[object] = mapped_column(
        TIMESTAMP(timezone=True), server_default=text("NOW()")
    )

    ticker: Mapped["Ticker"] = relationship(back_populates="headlines")
    sentiment_score: Mapped["SentimentScore"] = relationship(
        back_populates="headlines"
    )

    __table_args__ = (
        CheckConstraint(
            "source IN ('finnhub','yahoo_finance','marketwatch','seeking_alpha',"
            "'investing_com','wsj','google_news','coingecko')",
            name="ck_headlines_source",
        ),
        CheckConstraint(
            "individual_sentiment IN ('positive','negative','neutral')",
            name="ck_headlines_sentiment",
        ),
        CheckConstraint(
            "confidence IN ('high','medium','low')",
            name="ck_headlines_confidence",
        ),
        Index("idx_headlines_ticker_id", "ticker_id"),
        Index("idx_headlines_sentiment_score_id", "sentiment_score_id"),
        Index("idx_headlines_published_at", text("published_at DESC")),
    )


class MarketMover(Base):
    __tablename__ = "market_movers"

    id: Mapped[str] = mapped_column(UUID(as_uuid=True), **_UUID_PK)
    asset_class: Mapped[str] = mapped_column(String(20), nullable=False)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    price: Mapped[float] = mapped_column(Float, nullable=False)
    change_pct: Mapped[float] = mapped_column(Float, nullable=False)
    fetched_at: Mapped[object] = mapped_column(
        TIMESTAMP(timezone=True), server_default=text("NOW()")
    )

    __table_args__ = (
        CheckConstraint(
            "asset_class IN ('stock','crypto','commodity')",
            name="ck_movers_asset_class",
        ),
        CheckConstraint(
            "direction IN ('gainer','loser')",
            name="ck_movers_direction",
        ),
        Index("idx_movers_asset_class", "asset_class"),
        Index("idx_movers_fetched_at", text("fetched_at DESC")),
    )


async def get_session() -> AsyncSession:
    """FastAPI dependency yielding an async session."""
    async with AsyncSessionLocal() as session:
        yield session


async def init_db() -> None:
    """Create the pgcrypto extension (for gen_random_uuid) and all tables."""
    async with engine.begin() as conn:
        await conn.execute(text("CREATE EXTENSION IF NOT EXISTS pgcrypto"))
        await conn.run_sync(Base.metadata.create_all)
        # create_all won't alter an existing table — add columns introduced
        # after first deploy here (idempotent).
        await conn.execute(
            text("ALTER TABLE sentiment_scores ADD COLUMN IF NOT EXISTS summary TEXT")
        )
